/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the local application boundary is available.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Methods
         * @description List all current engineering methods for reference and frontend handshake.
         */
        get: operations["list_methods_api_v1_methods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/methods/{method_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Method
         * @description Return one language-neutral engineering method definition.
         */
        get: operations["get_method_api_v1_methods__method_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description Stable structured error detail for API clients.
         */
        ApiError: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message Key */
            message_key: string;
        };
        /**
         * ApiErrorResponse
         * @description Stable error envelope returned by the API boundary.
         */
        ApiErrorResponse: {
            detail: components["schemas"]["ApiError"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Minimal service health response.
         */
        HealthResponse: {
            /**
             * Api Version
             * @default v1
             */
            api_version: string;
            /** Application Version */
            application_version: string;
            /**
             * Service
             * @default hcmcalc-api
             */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * MethodDefinitionResponse
         * @description Public engineering metadata; no frontend delivery status is implied.
         */
        MethodDefinitionResponse: {
            /** Availability */
            availability: string;
            /** Capabilities */
            capabilities: string[];
            /** Chapter Reference */
            chapter_reference: string;
            /** Description Key */
            description_key: string;
            /**
             * Engineering Available
             * @default true
             */
            engineering_available: boolean;
            /** Family */
            family: string;
            /** Hcm Chapter */
            hcm_chapter: string;
            /** Hcm Edition */
            hcm_edition: string;
            /** Input Contract */
            input_contract: string;
            /** Legacy Workflow */
            legacy_workflow?: string | null;
            /** Method Id */
            method_id: string;
            /** Method Identifier */
            method_identifier: string;
            /** Method Version */
            method_version: string;
            /** Name Key */
            name_key: string;
            /** Scope Summary Keys */
            scope_summary_keys: string[];
            /** Supported Unit Systems */
            supported_unit_systems: ("metric" | "imperial")[];
        };
        /**
         * MethodsResponse
         * @description Stable envelope for method discovery.
         */
        MethodsResponse: {
            /** Methods */
            methods: components["schemas"]["MethodDefinitionResponse"][];
            /**
             * Registry Version
             * @default r1
             */
            registry_version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_methods_api_v1_methods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodsResponse"];
                };
            };
        };
    };
    get_method_api_v1_methods__method_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                method_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodDefinitionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
